### ISSUE TITLE
请问 EPUB 能用我修改的这个版本吗

### ISSUE THREAD

**Issue by 4399LX** [liuli-moe/to-the-stars#102]
请问 EPUB 能用我修改的这个版本吗？
不过我这个版本的文本内容是半年前的（2024年5月20日）；

当时下载后，觉得格式太乱，于是整理了一下，没想过断更许久的翻译还会再更新。
今天偶然发现更新了翻译，其中修正了许多错漏内容，

但又不想重新折腾，所以发给你们来修改，或者用作参考。

使用软件：EPUB 电子小说编辑器 Sigil v1.4.3

链接: https://pan.baidu.com/s/1z-ZMGPyD60pXQhGJ3RF2qg?pwd=xcwi
提取码: xcwi

![截图01](https://github.com/user-attachments/assets/c228e61f-812c-4736-a0b8-69f871986872)　　![截图02](https://github.com/user-attachments/assets/6a9a08ef-3566-471b-936a-45aa334ebd1e)　　![截图03](https://github.com/user-attachments/assets/77b3b494-22de-4e39-8aae-e54d687beb98)　　![截图04](https://github.com/user-attachments/assets/8dbbfb28-ac8e-4ddf-b507-d769ce013a09)

**Comment by rxliuli** [comment]
如果有任何错误修复，请基于当前 repo 的最新版本直接提 PR

**Comment by 4399LX** [comment]
> 如果有任何错误修复，请基于当前 repo 的最新版本直接提 PR，参考
> 
> #102

没看懂什么意思，我说的错漏修正是指其中某些 句子、标点符号 的修改，但我又不知道哪些被修改了，重新看一遍太耗精力了，所以发给你们来参考修正。

就算不用我的版本，参照一下，修改整理 books 1.7.34 的EPUB格式也是好的。

**Comment by rxliuli** [comment]
> > 如果有任何错误修复，请基于当前 repo 的最新版本直接提 PR，参考
> > #102
> 
> 没看懂什么意思，我说的错漏修正是指其中某些 句子、标点符号 的修改，但我又不知道哪些被修改了，重新看一遍太耗精力了， 所以发给你们来参考修正。
> 
> 就算不用我的版本，参照一下，修改整理 books 1.7.34 的EPUB格式也是好的。

是的，如果你不知道哪些被修改的话，其他人也更难知道，所以最好修改你记得的错误，并提出一个 PR，这样它就会自动更新网站并发布新的 epub。

**Comment by 4399LX** [comment]
这个语句……机翻？算了，不重要。

从你说的意思来看，books 1.7.34 是网站自动整理发布的，幕后没有人在编辑制作 EPUB 电子书籍？
好吧，看来还是要自己动手。

**Comment by iolliotier** [comment]
你这个epub如果是一年前下载的，那很多修正可能只是造轮子，当时很多旧错误现在已经修复了，如果有这边没发现但你发现并修复了的错误，欢迎提出来

**Comment by 4399LX** [comment]
有点奇怪，是我没描述清晰吗？


我说的 “修正” 仅仅是指 EPUB 的排版设计修改，示意图片也贴上了。
“翻译” 也是指不能轻松将旧翻译替换为新翻译。


而不是我自己去进行小说翻译，因为我不怎么懂英文。

**Comment by 4399LX** [comment]
> 你这个epub如果是一年前下载的，那很多修正可能只是造轮子，当时很多旧错误现在已经修复了，如果有这边没发现但你发现并修复了的错误，欢迎提出来

有点奇怪，是我没描述清晰吗？

我说的 “修正” 仅仅是指 EPUB 的排版设计修改，示意图片也贴上了。
“翻译” 也是指不能轻松将旧翻译替换为新翻译。

而不是我自己去进行小说翻译，因为我不怎么懂英文。

**Comment by andylizi** [comment]
我确认一下，没理解错的话，你指的排版设计修改，如图片所示，是增加了“封面”、”作品简介“、“概要”、“项目简介”、和“目录”这五个 epub 章节，除此之外没有别的改动（至少从图中看不出别的）？

**Comment by 4399LX** [comment]
> 我确认一下，没理解错的话，你指的排版设计修改，如图片所示，是增加了“封面”、”作品简介“、“概要”、“项目简介”、和“目录”这五个 epub 章节，除此之外没有别的改动（至少从图中看不出别的）？

还有增加了 文本缩进2格，标题大小和位置的调整，图片大小缩放和居中。

就没有了，毕竟只是为了自己阅读舒适的简单调整。
主要还是整理了EPUB中乱码般的html，改为数字排序，方便做调整。

**Comment by iolliotier** [comment]
你这个真无必要，第一，你的epub是下载一年前的旧版本，那会很多章节都没翻译，不管做什么修改，都不能直接放release的，第二，行首缩进可以在阅读软件里调整，排版、目录和章节名可以在epub打包规则里优化，这个可以以后做，关键问题你没搞清

**Comment by 4399LX** [comment]
> 你这个真无必要，第一，你的epub是下载一年前的旧版本，那会很多章节都没翻译，不管做什么修改，你这个epub都不能直接放release的，第二，行首缩进可以在阅读软件里调整，排版、目录和章节名可以在epub打包规则里优化，这个可以以后做，关键问题你没搞清

你好，我以最新的作品翻译版本 1.7.37 重新制作了epub，应该可以用吧？

链接: https://pan.baidu.com/s/13A7GVBlznLS_AhKaAd-3hA?pwd=czwd
提取码: czwd

**Comment by iolliotier** [comment]
> > 你这个真无必要，第一，你的epub是下载一年前的旧版本，那会很多章节都没翻译，不管做什么修改，你这个epub都不能直接放release的，第二，行首缩进可以在阅读软件里调整，排版、目录和章节名可以在epub打包规则里优化，这个可以以后做，关键问题你没搞清
> 
> 你好，我以最新的作品翻译版本 1.7.37 重新制作了epub，应该可以用吧？
> 
> 链接: https://pan.baidu.com/s/13A7GVBlznLS_AhKaAd-3hA?pwd=czwd 提取码: czwd

如果有新PR被合并，就算替换掉release的epub，新归档打包一发布你这个就又被覆盖了，不如你把改写规则提交上来，看看能不能写在epub合并程序的规则里

**Comment by 4399LX** [comment]
> 如果有新PR被合并，就算替换掉release的epub，等新归档打包一发布你这个就又被覆盖了，不如你把改写规则提交上来，看看能不能写在epub合并程序的规则里

啊，这个我不懂唉，只是想让现在这个版本能看起来舒适点，后续其它的不考虑。

要不你改一下，只增加两个修改规则就好，
1、标题居中；2、行首缩进两格

**Comment by andylizi** [comment]
> 要不你改一下，只改一个修改规则就好，行首缩进两格。

首行缩进2字符是印刷品的排版习惯，不适合电子书。具体原因这个知乎问题讲的挺清楚： [为什么网上的文章越来越少采用首行缩进了？](https://www.zhihu.com/question/539160773)

**Comment by iolliotier** [comment]
> > 如果有新PR被合并，就算替换掉release的epub，等新归档打包一发布你这个就又被覆盖了，不如你把改写规则提交上来，看看能不能写在epub合并程序的规则里
> 
> 啊，这个我不懂唉，只是想让现在这个版本能看起来舒适点，后续其它的不考虑。
> 
> 要不你改一下，只改一个修改规则就好，行首缩进两格。

文本里不采取行首缩进是有原因的，因为在web3文本上编辑，粗体符号和分割线符号如果前面加了空符号就失效了，如果想获得更好的阅读效果，行首缩进可以软件里调

**Comment by 4399LX** [comment]
> 文本里不采取行首缩进是有原因的，因为在web3文本上编辑，粗体符号和分割线符号如果前面加了空符号就失效了，如果想获得更好的阅读效果，行首缩进可以软件里调

好的，我已经明白了

**Comment by iolliotier** [comment]
这位老兄，如果issue里问题解决的话，就可以关闭了，怎么关闭又打开了
