### ISSUE TITLE
Chp 56与后续章节的校对问题

### ISSUE THREAD

**Issue by ArgusK17** [liuli-moe/to-the-stars#14]
在阅读Chp 56的时候发现了不少格式错误，包括但不限于：
- 日语敬称/昵称：在文中写作“XX-酱/桑”，应统一为“XXちゃん/さん”
- bacanno同学的碎碎念需要删除
- 许多“XX说”后缺标点或标点错误，这一错误非常常见

虽然针对这些章节的重译已经在进行，但是进度感人，预计1年1章，因此对现有翻译的基本修正还是十分必要

**Comment by rxliuli** [comment]
嘛，之前也处理过一部分，例如**克莱丽丝、鄂温马克**之类的人名，但遗漏的应该很多吧。话又说回来，总不会比原作者的进度更慢吧（已经 9 年了，有生之年系列无疑
