### ISSUE TITLE
关于建立一个评论区的可行性

### ISSUE THREAD

**Issue by ArgusK17** [liuli-moe/to-the-stars#17]
介于现在在线站成为了主要的阅读途径，过去相当有趣的B站专栏评论就不复存在了。尽管群友们也会在群里给一些反馈，但与写下来固定的评论还是有所不同。不过不知道这个功能的实现难度如何。

梨子兄之前提供了一份参照，供参考：
https://github.com/utterance/utterances

**Comment by andylizi** [comment]
utterances 的主要问题在于它得注册 Github 账号才能评论，这个要求对于绝大多数读者来说不太现实。

目前网站只需要提供静态页面，因此用的应该是免费的 Github Pages 套一层 Cloudflare 。但评论系统如果自建的话肯定是要额外服务器处理的，开发起来相对静态网站也要复杂不少（虽然有不少现成的实现可以拿过来用）。不过访问量这么小的话， Cloudflare Workers 免费版也不是不能用吧。第三方服务我没了解过，但收费估计是免不了的。utterances 这种利用 Github 财大气粗的设计是少有的例外。

然后就是流程上的问题。比如说评论要不要登录？用户乐不乐意为了评论个同人小说专门去注册暂且不管。开发的复杂度又上去了一层。不要登录也可以，国外很多博客确实是填个邮箱就能留言的。但无论怎么设计，验证码和流量限制是必不可少的，否则数据库分分钟被打爆。

最后是国内的特色问题，内容审核怎么办。所有带UGC功能的国内互联网公司，做到一定规模后都免不了要投入可观的人力物力去做内容审查，否则举报一个一个准。当然我相信就我们这点访问量，不会有人那样闲得无聊哈。但前车之鉴真的不少：https://www.zhihu.com/question/393725770

说了这么多，我的观点可以总结成一句话：吃力不讨好，还是别折腾了XD

**Comment by ArgusK17** [comment]
实际上设想中也不是想要一个自由讨论的评论区，而是更接近于“精选留言”的这么一类东西。本质上是希望读者在读完正文后还能看到一些他人的反应或是感想。
既然不需要实时更新，那么许多审查之类的就不是难事。何况我们流量这么小。

**Comment by rxliuli** [comment]
吾辈已经集成了 [giscus](https://giscus.app/) 评论系统，可以帮忙测试一下是否可用么？@ArgusK17

**Comment by ArgusK17** [comment]
我试了一下没有问题
不过这些垃圾评论要怎么删除呢（笑）

**Comment by rxliuli** [comment]
> 我试了一下没有问题 不过这些垃圾评论要怎么删除呢（笑）

在 github 评论区可以删除掉，ref: https://github.com/liuli-moe/to-the-stars/discussions/18

![image](https://user-images.githubusercontent.com/24560368/189640270-eae6608f-2b72-4f0d-ab2c-0eea7a40149a.png)
