### ISSUE TITLE
物理学专有名词翻译校正

### ISSUE THREAD

**Issue by rxliuli** [liuli-moe/to-the-stars#30]
这几章的翻译质量是难以接受的，由于我的中文和英文水平限制，这里我只提出一些物理学相关的修改意见。

> 旋转频率约为 300 赫兹，表面磁场仅为 10^4T，半径为 10 公里

此处的单位建议统一为中文或者字母

> 别忘了，当你离恒星越来越近时，辐射将与 r^2 成比例增加，并准备好接受小型无人驾驶飞机性能下降的影响。

这里的辐射不是与 $r^2$ 成比例而应该是 $r^{-2}$，原文中有一些歧义

> 脉冲星故障

pulsar glitch 应该翻译为脉冲星的自转突变，说一个自然天体有故障也太奇怪了

> 同样，r^2 也适用。

原文中为 $r^3$，指的是磁场强度会随距离的立方衰减。将脉冲星近似为磁偶极子也应该是 $r^3$

> 撞击本身几乎无足轻重，十亿吨级的光子很容易被中子甩掉，在超过一秒的时间内被潮汐力拉伸，从而撕裂船只。
The impact itself would hardly matter, gigaton blips easily shrugged off by neutronium, stretched out over a second or so by tidal shear tearing the ships apart.

这里光子被中子甩掉是不正确的，因为中子内部不含有光子，这种说法很奇怪。原文中的 blip 查到的含义有 something relatively small or inconsequential within a larger context，应该是船体的碎块；neutronium 指的是纯由中子构成的物质而不是中子本身，这里可能指的是中子星（不确定）。这句原文我也没读懂，但这个翻译肯定有问题。

> 异界物质

应为奇异物质，小说中虚构的用于超光速引擎的物质

>脉冲星会出故障

同上，glitch 应为自转突变

>当激活它的时候，阿姆斯特朗计划的星门组件的大小几乎是原来 Adept Blue 的 20 倍

Adept Bule 指的是蓝色大师空间站

> 但是对于所有的异界物质控制单元和 IIC 优化互连和排除锁定力场以及散布在结构上的场操纵驱动器来说

同上，奇异物质

> 这里不再是黑洞表面 {event horizon}

event horizon 有专门的翻译视界或者事件边境，指的是逃逸速度大于光速，无法脱离黑洞的地方。翻译成表面也不能说错，只是不太严谨。

> 其中矿场丢弃了储存的时空碎片，或者自爆从而引发了脉冲星故障

同上，glitch 应为自转突变

除了一些错误的翻译，这几章还有明显的语序不自然和严重的翻译腔。我的词汇量明显不足流畅阅读原文，中文水平也不能保证自行翻译的质量。如果有重新翻译这几章的计划，我愿意加入并提供一些物理学相关的帮助。

_Originally posted by @name8102 in https://github.com/liuli-moe/to-the-stars/discussions/29#discussioncomment-5162757_

**Comment by MADOKAAAAA** [comment]
58-61章按计划都是要重译的，暂定按顺序来，只是目前人手不足。当然也可以先做后面，你可以建好石墨文档发到翻译群里。

**Comment by name8102** [comment]
我只是在阅读中发现了一些问题并指出，但我没有翻译和写作经验，也不清楚自己的文笔能不能独立完成大段的翻译。
如果有需要的话我可以维护一个物理学名词对照表，也愿意加入翻译群的讨论。

**Comment by ArgusK17** [comment]
翻译群目前不被搜索，你可以先进读者群然后我拉你进翻译群

**Comment by rxliuli** [comment]
有人考虑使用 chatgpt 辅助润色翻译么？
下面是一个润色前后的对比

```md
就物理学而言，瞬时星际通信中继网络（俗称 IIC）是执政体的的一大胜利，是人类技术水平和对自然掌握能力的有力证明。仅需要一个普朗克单位宽的，能够跨越星际的虫洞，就可用于比光速更快的通讯，这真是一个奇迹。

然而，在实际使用方面，IIC 网络是非常便捷的，至少在无视实现和部署的种种细节之后。它遵循以下一系列基本性质：

每一个链接都是点对点的 {point‐to‐point.P2P}
每个链接的带宽受当前光子传输技术的限制。
链接经过的物理距离越远，维护所需的能量就越多。
只能在非常近的距离建立新的链接。（按目前的技术，约 7000 公里，在深空中更远）
这里我们称之为链接而不是虫洞，因为实际上 IIC 为了增加带宽而同时使用多个虫洞，我们可以假设每个链接的总带宽为保证其通用性而受到系统维护虫洞能力的限制。

这些特性结合起来，确保网络的底层架构即使是几个世纪前的网络工程师也不会陌生。最大、最昂贵的连接是行星 IIC 中继器之间的链接，巨大的结构能够维持众多的星际虫洞，并为大量的交通服务。它们充当了巨大路由器的角色，使用永久性链接来联通行星与行星、行星与空间站等等。较低级别的二次链接将较小的装置链接到较大的装置上，尽管这里必须指出，光速传输对于大多数行星范围内的应用来说已经相当适用了。

这种固定的拓扑结构适合永久性设施和行星，但民用船只和舰队呢？一开始是如何建立新的链接的？

在这里，我们必须依赖 IIC 节点的能力来生成新的链接，并相对容易地注销旧有的，但关键的限制是初始链接必须在短距离内形成。星际飞船通过它们的 IIC 节点与行星中继器形成并依赖新的链接，直到它们接入下一个系统。

维持这种链接的能源成本仍然适用，编队、民用或军用的舰船将依靠较大的舰船来维持遥远的星际链接，同时在它们之间使用更短程的本地 IIC 链接。在军事用途中，这会带来一个额外的好处，即为舰队机动提供即时的、几乎不受干扰的通信，只需在最近的战斗巡洋舰或巡洋舰之间进行一些高度优化的信息跳跃。

虽然 IIC 的大量军事应用促进了网络的快速扩展，但接触战争暴露了以前没有深入考虑过的技术局限性问题。例如，改进的重力传感器在考虑到隐身技术的情况下，排除了使用除最短距离链接以外的所有链接。更令人失望的是，如果没有根本性的突破，基础科学可能会走到死胡同。多亏了俄狄浦斯之战的数据，以及与俄狄浦斯的英雄 —— 志筑良子一起进行的研究，现在人们普遍怀疑章鱼们的大型虫洞和悖论引擎是根据不同的原理运作的。

因此，执政体：科学技术将他战时对 IIC 研究的巨额投资缩减了一部分，转而将资源投入到虫洞生成和基础时空物理学的相邻研究中。尽管如此，对 IIC 的一些研究仍在继续，尤其是在降低带宽成本比方面。

—— 节选，“IIC 网络导论”，七年级阅读材料
```

润色之后

```md
在物理学上，瞬时星际通信中继网络（通常称为 IIC）是执政体治理的一项胜利，是人类技术能力和对自然掌握程度的生动证明。以普朗克宽度为基础的虫洞可以跨越星际，用于实现超光速通讯，这绝对是一种奇迹。

但是，在实际使用方面，IIC 网络相当简单，至少在远离实现和部署细节后。它具有以下基本属性：

每个连接都是点对点的（point-to-point）。
每个连接的带宽受光子传输技术限制。
连接穿过的物理距离越远，维护所需的能量就越多。
新连接只能从非常短的距离建立（目前技术约为 7000 公里，在深空中距离更远）。
我们在此称其为 “连接”，而不是 “虫洞”，因为实际上 IIC 网络同时使用多个虫洞以增加带宽。我们可以假定每个连接的总带宽受系统维护虫洞能力限制，以保证其通用性。

这些属性结合在一起，保证了网络底层结构即使对于数个世纪前的网络工程师而言也很熟悉。最大、最昂贵的连接是行星级 IIC 中继器之间的连接，它们是能够维持大量星际虫洞的巨大建筑，可服务于大量的通讯流量。它们充当了巨大的路由器，通过永久连接联通行星和空间站等。更便宜的次要连接连接较小的设施和较大的设施，但需要注意的是，对于大多数行星级应用来说，光速传输已经足够了。

这种固定的拓扑结构适合于永久设施和行星，但对于民用船舶和舰队呢？首先，新连接是如何建立的？

在这里，我们需要依靠 IIC 节点相对容易地建立和注销旧连接的能力。但关键限制是初始连接必须在短距离内建立。星际飞船通过其 IIC 节点在飞越时与星际中继器建立新连接，然后依赖这些连接直到到达下一个系统。

这种连接的能源成本仍然适用，编队、民用或军用的舰船将依靠较大的舰船来维护远距离的星际连接，同时在它们之间使用更短的本地 IIC 连接。在军事环境中，这带来了一个额外的好处，即为舰队提供即时、几乎不受干扰的通信，只需在最近的战斗巡洋舰或巡洋舰之间进行几次高度优化的跃迁即可。

尽管 IIC 的许多军事应用促进了网络的快速扩展，但接触战争暴露出了以前没有深入考虑的技术局限性问题。例如，改进的重力感应技术在考虑到隐身技术时排除了除最短距离链接以外的所有链接。更令人失望的是，除非有基础性突破，否则底层科学可能已经走到了死胡同。感谢奥菲乌斯之战的数据和与奥菲乌斯英雄志筑良子的研究，现在人们普遍怀疑章鱼们的大型虫洞和悖论驱动器是由不同的原理运作的。

因此，执政：科学与技术将部分战时投资从 IIC 研究中撤回，将资源转向虫洞形成和基础时空物理学的相邻研究。尽管如此，对 IIC 的研究仍在进行中，特别是在降低成本与带宽比例方面。
```
