### ISSUE TITLE
请问在线阅读网站的文章可以通过RSS订阅吗？

### ISSUE THREAD

**Issue by BloodBladeW** [liuli-moe/to-the-stars#32]
如题，如果能用RSS订阅的话，可以及时收到更新还是比较方便的。

**Comment by rxliuli** [comment]
吾辈简单搜索了一下，暂时没有找到直接可用的方法。

---

吾辈编写了一些代码，现在有了最基本的 rss.xml 支持，你可以通过订阅 https://tts.liuli.moe/rss.xml 来看到

**Comment by andylizi** [comment]
不需要把每一章的完整内容都放进去吧……现在这个 `rss.xml` 体积有 5.3MB（brotli 后也有 2.1M），每次检查更新都下载一遍也太离谱了。

**Comment by rxliuli** [comment]
> 不需要把每一章的完整内容都放进去吧……现在这个 `rss.xml` 体积有 5.3MB（brotli 后也有 2.1M），每次检查更新都下载一遍也太离谱了。

或许应该只包含最后 20 个发布的章节

**Comment by rxliuli** [comment]
@andylizi @BloodBladeW 已修改为仅包含最后 10 章，大小不到 1M

**Comment by BloodBladeW** [comment]
> @andylizi @BloodBladeW 已修改为仅包含最后 10 章，大小不到 1M

非常感谢，另外有个建议是可以把订阅链接放在首页里面，这样后来者就可以直接看到了。

**Comment by rxliuli** [comment]
> > @andylizi @BloodBladeW 已修改为仅包含最后 10 章，大小不到 1M
> 
> 非常感谢，另外有个建议是可以把订阅链接放在首页里面，这样后来者就可以直接看到了。

已更新首页，添加了 rss 链接
