### ISSUE TITLE
文章格式校正计划

### ISSUE THREAD

**Issue by rxliuli** [liuli-moe/to-the-stars#4]
目前除第一章和番外之外，所有**粗体**、*斜体*格式均未正确保留，所以需要重新校对，将从以下几个来源进行校对

1. 百合会论坛：<https://bbs.yamibo.com/forum.php?mod=viewthread&tid=206113&extra=&authorid=61676>，主要来源，在第三卷 54 章之前应该主要参考这里
2. bilibili：<https://www.bilibili.com/read/cv692285>，第三卷 54 章之后需要参考这里

如果有人愿意帮忙一起处理，请在该 issue 下面回复，吾辈将会在对应章节后 @用户名 以避免重复处理。请使用 github diff 对比并保留之前的错误修复，避免修复了格式却让之前的错误重现，尤其是和谐的部分请留意修正。在所有章节完成校正之后将发布新的 epub，在此之前，所有格式的修复仅发布至线上网站。

如果你是从网页转换的，则下面有一些校正指南可以参考

- 保证 github markdown 预览时格式是正确的
- 更改 `* * *` 为 `---` 用于章节分割
- 清除行尾额外的空格，一般是两个，这被用于 markdown 换行使用，但在这里不需要，例如 `〈在下文中，〈〉① 中的内容需要拥有相应阅览等级才能查看。圈内的数字代表所需的密级。〉 ①  ` => `〈在下文中，〈〉① 中的内容需要拥有相应阅览等级才能查看。圈内的数字代表所需的密级。〉 ①`
- 如果一段加粗的文本以标点符号结尾并且后面有中文，则需要在后面加一个空格，例如 `**真没想到我这么快就要死了，**她有些自暴自弃地想着。` => `**真没想到我这么快就要死了，** 她有些自暴自弃地想着。`
- 每个章节开头的一些引用和虚拟文献不需要使用 `>` 表示引用，仅需要在正文开始之前添加 `---` 分割即可，原作即是如此，参考：<https://www.fanfiction.net/s/7406866/63/To-the-Stars>
- 第三卷 54 章之后还需要结合英文原作确定分割线的位置，因为翻译中的分割线存在缺失

第一卷

- [x] 第一章 许愿 - 量子纠缠 -- @andylizi
- [x] 第二章 幻影 -- @rxliuli
- [x] 第三章 麻美观影记 上 -- @rxliuli
- [x] 第四章 麻美观影记 下 -- @rxliuli
- [x] 第五章 家人 -- @rxliuli
- [x] 第六章 军队 -- @rxliuli
- [x] 第七章 南方组 -- @rxliuli
- [x] 第八章 政与教 -- @rxliuli
- [x] 第九章 回声 -- @rxliuli
- [x] 第十章 准将 -- @rxliuli
- [x] 第十一章 以往生活的残骸 -- @rxliuli
- [x] 第十二章 狩猎魔兽的人 -- @rxliuli
- [x] 第十三章 不对等的信息 -- @rxliuli
- [x] 第十四章 血缘 -- @rxliuli
- [x] 第十五章 萨姆萨拉 -- @rxliuli
- [x] 第十六章 属于天空的光芒 -- @rxliuli

第二卷

- [x] 幕间一 无间迷梦 -- @rxliuli
- [x] 第十八章 落地 -- @rxliuli
- [x] 第十九章 回天 -- @rxliuli
- [x] 第二十章 相对论 -- @rxliuli
- [x] 第二十一章 突变 -- @rxliuli
- [x] 第二十二章 变化的风向 -- @rxliuli
- [x] 第二十三章 失去的爱 -- @rxliuli
- [x] 第二十四章 历史学家 -- @rxliuli
- [x] 第二十五章 穿破天空 -- @rxliuli
- [x] 第二十六章 红与绿的血 -- @rxliuli
- [x] 第二十七章 那些璀璨的明星 -- @rxliuli
- [x] 第二十八章 不屈吾魂 -- @rxliuli
- [x] 第二十九章 救世之女 -- @rxliuli
- [x] 第三十章 权力与使命 -- @rxliuli
- [x] 第三十一章 爱的形式 -- @rxliuli
- [x] 第三十二章 选择与未来 -- @rxliuli

第三卷

- [x] 幕间二 小玛德莱娜 -- @rxliuli
- [x] 第三十四章 造就我们的那些羁绊 -- @rxliuli
- [x] 第三十五章 伤亡 -- @rxliuli
- [x] 第三十六章 追逐幻影 -- @rxliuli
- [x] 第三十七章 炽天使 -- @rxliuli
- [x] 第三十八章 把握今天 -- @rxliuli
- [x] 第三十九章 无法愈合的伤痕 -- @rxliuli
- [x] 第四十章 镜之彼端 -- @rxliuli
- [x] 第四十一章 因与果 -- @rxliuli
- [x] 第四十二章 有光必有影 -- @rxliuli
- [x] 幕间 2.5 尘封的往事 上 -- @rxliuli
- [x] 幕间 2.5 尘封的往事 下 -- @rxliuli
- [x] 第四十五章 带电的肉体 -- @rxliuli
- [x] 第四十六章 轮中之轮 -- @rxliuli
- [x] 第四十七章 光明之城 -- @rxliuli
- [x] 第四十八章 知己知彼 -- @rxliuli
- [x] 第四十九章 过渡态 -- @rxliuli
- [x] 第五十章 玫瑰之下 -- @rxliuli
- [x] 第五十一章 永恒的求索 -- @rxliuli
- [x] 第五十二章 我们是谁 -- @rxliuli
- [x] 第五十三章 立场 -- @rxliuli
- [x] 第五十四章 永恒的青春 @ArgusK17
- [x] 第五十五章 新视点 -- @rxliuli
- [x] 第五十六章 脉冲星 -- @rxliuli
- [x] 第五十七章 三相点 -- @rxliuli
- [x] 第五十八章 托付信任 -- @rxliuli
- [x] 第五十九章 室内游戏 -- @rxliuli
- [x] 第六十章 数码预言 -- @rxliuli
- [x] 第六十一章 遁入虚空 -- @rxliuli
- [x] 第六十二章 消逝的光芒 上 -- @rxliuli
- [x] 第六十三章 消逝的光芒 下 @ArgusK17

**Comment by andylizi** [comment]
> * 那么第一作者为什么会使用粗体呢？

一个是B站不支持斜体……百合会不清楚，应该支持吧？

更重要的原因我觉得是，中文排版确实不适合使用<i>斜体</i>。英文<i>单词</i> 之间有空格分隔，再加上符号相对简单，因此看起来<i>不会</i>奇怪。但<i>中文</i>的话就感觉有点怪怪的，并且<i>突出效果</i>没那么明显。

**Comment by ArgusK17** [comment]
> * 每个章节开头的一些引用和虚拟文献不需要使用 `>` 表示引用，仅需要在正文开始之前添加 `---` 分割即可，原作即是如此，参考：https://www.fanfiction.net/s/7406866/63/To-the-Stars

这部分格式我参照的是AO3的版本，因为个人更喜欢这一版排版。
链接以供参考：https://archiveofourown.org/works/777002/chapters/79578916

另外“X卷完”的卷尾语也是作者自己写的呀，就这样删掉吗TAT

**Comment by ArgusK17** [comment]
> 记得修改一下第一章开头的引用格式，我是看梨子君这么弄所以也这样排的（

**Comment by ArgusK17** [comment]
关于斜体/粗体格式最后有定论了吗？我看chp 11~16更新的是粗体，但是chp 1 依旧是斜体（包括我自己更新的两章采用的也是斜体）

**Comment by rxliuli** [comment]
> 关于斜体/粗体格式最后有定论了吗？我看chp 11~16更新的是粗体，但是chp 1 依旧是斜体（包括我自己更新的两章采用的也是斜体）

吾辈倾向于保持粗体，虽然斜体可以有另一种区分，但校正速度要慢的多（因为现有的翻译都是粗体，需要将念话、脑内通讯以及思想部分转换为斜体），而且如 @andylizi 所言，中文斜体的突出效果并不明显

**Comment by ArgusK17** [comment]
> 保持粗体

那我稍后修改一下

**Comment by ArgusK17** [comment]
> * 如果一段加粗的文本以标点符号结尾并且后面有中文，则需要在后面加一个空格，例如 `**真没想到我这么快就要死了，**她有些自暴自弃地想着。` => `**真没想到我这么快就要死了，** 她有些自暴自弃地想着。`

这样做的原因是什么呢？如果是斜体还可以理解为保持恰当间距，但是对粗体这样做似乎并没有改善观感，反而会显得间隔过大。

**Comment by andylizi** [comment]
这其实是个技术问题……很多 markdown 渲染器是针对西语环境设计的，即两个单词之间一定有空格或者（英文）标点符号。因此它故意设计成只在前后有空格或标点的`*`、`_`等时才会被识别处理。这样做的目的是避免一些 false positive，例如 `3*2=6` 里面的`*`被识别成样式，而且设计者想着反正你也不会需要加粗单词的某一部分（li<i><b>ke th</b></i>is）嘛。但是这显然就对不用空格的语言十分不友好。加空格只是曲线救国的手段。

其实如果能够选择自己 markdown 被渲染的环境并且不用考虑兼容性的话，比如说自建站点或者用一个已知不要求空格的站点，那么不加空格也没问题，而且正如你所说能改善观感。只可惜很多时候我们没法选……

**Comment by rxliuli** [comment]
> 这其实是个技术问题……很多 markdown 渲染器是针对西语环境设计的，即两个单词之间一定有空格或者（西文）标点符号。因此它故意设计成只有前/后带空格或西文标点的`*`、`_`等才会被识别处理。这样做的目的是避免一些 false positive，例如 `3*2=6` 里面的`*`被识别成样式，而且设计者想着反正你也不会需要加粗单词的某一部分（like this）嘛。但是这显然就对不用空格的 CJK 语言十分不友好。加空格只是曲线救国的手段。
> 
> 其实如果能够选择自己 markdown 被渲染的环境并且不用考虑兼容性的话，比如说自建站点或者用一个已知不要求空格的站点，那么不加空格也没问题，而且正如你所说能改善观感。只可惜很多时候我们没法选……

是的，这个问题吾辈也曾考察过，遗憾的是，markdown 的标准如此，已知只有 marked 能正确处理这种情况，甚至 github 都不行，这确实很烦人，但目前没有太好的解决方案

**Comment by rxliuli** [comment]
某种可行的方法是将 `**真没想到我这么快就要死了，**她有些自暴自弃地想着。` 替换为 `**真没想到我这么快就要死了**，她有些自暴自弃地想着。`。但这并不总是可行的，例如以 ？或 ！结尾的

**Comment by rxliuli** [comment]
目前，粗体后面的空格已经通过 markdown-it 插件清除，目前源 markdown 文档仍然必须添加额外的空格，但在渲染成网页时会被自动清理，参考：<https://github.com/markdown-it/markdown-it/issues/880#issuecomment-1188616512>。渲染 epub 目前还没有太好的方法，但预期会通过 [epub-gen](https://github.com/cyrilis/epub-gen) 的工具来处理以便插件自定义的渲染逻辑。

**Comment by rxliuli** [comment]
第三卷已处理一半左右。。。

**Comment by rxliuli** [comment]
格式已全部校验完成，ref: <https://github.com/liuli-moe/to-the-stars/releases/tag/1.2.0>

**Comment by rxliuli** [comment]
> 渲染 epub 目前还没有太好的方法，但预期会通过类似 [epub-gen](https://github.com/cyrilis/epub-gen) 的工具来处理以便插件自定义的渲染逻辑。

基本的 epub 生成工具已实现，稍晚一点我将实用并生成新的 epub，以解决上面提到的多余空格的问题

**Comment by rxliuli** [comment]
已修正，ref: <https://github.com/liuli-moe/to-the-stars/releases/tag/1.4.0>

**Comment by ArgusK17** [comment]
重开问题是因为找到了斜体的恰当处理方式。
参照一些实体书以及知乎回答，这方面比较好的做法似乎是用楷体/仿宋字体来替换原文中的斜体，对长句子和几个字的词汇效果都还不错，可以考虑对过去章节进行这方面的修改。目前简单比较似乎楷体效果不错。
[效果图](https://user-images.githubusercontent.com/60059745/188315004-0531d7ed-371b-4cfd-bbb9-93f2e87831b3.jpg)
[知乎链接](https://www.zhihu.com/question/20471777/answer/624741689)

不过github在这方面似乎支持的不是很好（？），可能需要单独处理一下，之后发布的章节或许也都要经过类似的处理。

**Comment by ArgusK17** [comment]
另外Andylizi指出一些密级标记的〈〉或许因为百合会的限制因此被改为了【】，个人也感觉〈〉更为美观一些。
可以考虑与上面的问题同步修改，不过上一个问题优先级更高。

**Comment by ArgusK17** [comment]
另外Andylizi指出一些密级标记的〈〉或许因为百合会的限制因此被改为了【】，个人也感觉〈〉更为美观一些。
可以考虑与上面的问题同步修改，不过上一个问题优先级更高。

**Comment by rxliuli** [comment]
> 重开问题是因为找到了斜体的恰当处理方式。
> 参照一些实体书以及知乎回答，这方面比较好的做法似乎是用楷体/仿宋字体来替换原文中的斜体，对长句子和几个字的词汇效果都还不错，可以考虑对过去章节进行这方面的修改。目前简单比较似乎楷体效果不错。

吾辈不太确定这是否是标准做法，修改 html render 可以做到这一点，但这在网页版可能会有些困难，因为中文字体一般都比较大

> 另外Andylizi指出一些密级标记的〈〉或许因为百合会的限制因此被改为了【】，个人也感觉〈〉更为美观一些。

这个处理起来相对简单很多，因为可以使用程序自动化处理，话虽如此，如果是**一些**的话，也需要逐个检查和替换就是了

**Comment by andylizi** [comment]
> 吾辈不太确定这是否是标准做法

确实很多这么做的。例如说 HPMOR 这部同人的[粉丝翻译](https://hpmor.xyz/hpmor_index/)：

<details>
<summary>点击展开</summary>

![](https://user-images.githubusercontent.com/12008103/188321822-5882da26-223a-40fd-88f7-f16cf7850a9c.png)
![](https://user-images.githubusercontent.com/12008103/188321820-2bf04737-0322-44c0-a268-42e664dc579a.png)

</details>

> 修改 html render 可以做到这一点，但这在网页版可能会有些困难，因为中文字体一般都比较大

比较大指的应该是 web font？确实CJK字体由于体积缘故是完全不适合像西文一样在线加载的，因此像“华文楷体”这种不可能。但是像宋体楷体这种还是足够普及的。

例如：

![c1](https://user-images.githubusercontent.com/12008103/188321920-35b07e3f-32b3-481c-b2c8-92bdeaf2490d.png)

**Comment by rxliuli** [comment]
> ![](https://user-images.githubusercontent.com/12008103/188321820-2bf04737-0322-44c0-a268-42e664dc579a.png)

吾辈看了一下，网页版似乎并没有这个效果，或许是吾辈访问的路径不对？ref: https://hpmor.xyz/hpmor_chp2/

![image](https://user-images.githubusercontent.com/24560368/188322579-4f9ca968-c8fd-4ff8-88b0-60d07035edf1.png)

**Comment by rxliuli** [comment]
> 另外 Andylizi 指出一些密级标记的〈〉或许因为百合会的限制因此被改为了【】，个人也感觉〈〉更为美观一些。

更新：吾辈检查了一下，仅有 20 个文件的 97 处需要处理，这似乎很简单

**Comment by rxliuli** [comment]
> > 另外 Andylizi 指出一些密级标记的〈〉或许因为百合会的限制因此被改为了【】，个人也感觉〈〉更为美观一些。
> 
> 更新：吾辈检查了一下，仅有 20 个文件的 97 处需要处理，这似乎很简单
> 
> ![image](https://user-images.githubusercontent.com/24560368/188323060-6d51ec63-9f31-4efd-a5bf-a0420b1554fa.png)

已完成

**Comment by andylizi** [comment]
> 怎么说呢，它们其实不太够，例如移动端就会炸掉

啊对……我没考虑移动端……

这确实就比较麻烦。想来想去，估计只能用 [font-spider](https://github.com/aui/font-spider/blob/master/README-ZH-CN.md) 或 [fontmin](https://github.com/ecomfe/fontmin) 这种提取子集的方案了。但搞这么复杂我不知道是否值得……

**Comment by rxliuli** [comment]
感觉比较复杂，所以暂时关闭这个 issue
