### ISSUE TITLE
关于 Grief cube 如何翻译的问题

### ISSUE THREAD

**Issue by rxliuli** [liuli-moe/to-the-stars#42]
有人提议修改之前的错误翻译“悲叹之种”修改为“悲叹立方”并提了 PR，https://github.com/liuli-moe/to-the-stars/pull/41

但通过搜索引用可以看到之前被更多人共识的引用

目前的提案

悲叹魔方 -- 非常多，第一页超过 28 个
<img width="730" alt="image" src="https://github.com/liuli-moe/to-the-stars/assets/24560368/9a1dbc53-6949-45f0-bd76-dbca710842ef">
同时魔兽篇漫画汉化也使用这个翻译。
![7bbfbebfcb399ff38b5235d9789c4c79](https://github.com/liuli-moe/to-the-stars/assets/24560368/c7dd8b9e-2d08-4c15-a515-4f8c5b358d68)

悲叹立方 -- 2 个引用
<img width="746" alt="image" src="https://github.com/liuli-moe/to-the-stars/assets/24560368/0d7c689b-ebd7-4070-a3d6-f8a1bbefd072">

悲叹核心 -- 没有引用
<img width="739" alt="image" src="https://github.com/liuli-moe/to-the-stars/assets/24560368/be62a990-a213-4c82-bd0f-6598ca3ffe80">

魔兽核心 -- 2 个引用，其中一个是 wiki
<img width="736" alt="image" src="https://github.com/liuli-moe/to-the-stars/assets/24560368/1ca17f1f-b0e2-4492-a41c-697c1d80cdc6">

悲叹之锭 -- 没有引用
<img width="714" alt="image" src="https://github.com/liuli-moe/to-the-stars/assets/24560368/02f74001-f56f-4bbb-b627-2a42e05a194b">

悲叹方块 -- 1 引用

<img width="725" alt="image" src="https://github.com/liuli-moe/to-the-stars/assets/24560368/8187f43c-660d-4e86-83f3-d22669e3f577">

**Comment by iolliotier** [comment]
有点疑问，原文人物在心灵感应对话时是以斜体标识的，以区别口头交谈，为什么修改版替换为粗体，是不是因为斜体在读取epub的阅读设备里不方便显示？

**Comment by iolliotier** [comment]
这些文字错误、错误粗体符号在github和网站上同时存在，需不需要我来核实校对并PR？可以的话我会采取修改版翻译为底稿并逐一进行正确修订

**Comment by rxliuli** [comment]
> 提示：早期个人引用文句时制造了一个复制错误，之前没有及时发现，现在看到它在修改版翻译里居然照样存在，请修改！
> 
> 文章原句：
> 
> > “与其让这些谜团与阴谋继续困扰着我和良子，我宁愿彻底消灭它们，这样，等她回来的时候，我们就不必再生活在他当蛇形无人机困惑地抬头看上去时们的阴影之下了。” 亚纱美摇了摇头。
> 
> 正确句子：
> 
> > “与其让这些谜团与阴谋继续困扰着我和良子，我宁愿彻底消灭它们，这样，等她回来的时候，我们就不必再生活在他们的阴影之下了。” 亚纱美摇了摇头。
> 
> 第二个错误：当初后期打到这段句子时某一句型没写完，只写了个**参天大树**，请替换完整的句子！
> 
> 文章原句：
> 
> > 当她们进入覆盖栖息地的森林部分时，环境发生了显著的变化。原本的草地和阳光消失，参天大树，随着她们的深入，树木变得越来越密集，树枝几乎触及车厢，却又好像被某种无形力量隔开般退避开来。
> 
> 正确句子：
> 
> > 当她们进入覆盖栖息地的森林部分时，环境发生了显著的变化。原本的草地和阳光消失，只剩下遮天蔽日的参天大树，随着她们的深入，树木变得越来越密集，树枝几乎触及车厢，却又好像被某种无形力量隔开般退避在一旁。

可以直接提 pr 直接修改。

**Comment by rxliuli** [comment]
> 有点疑问，原文人物在心灵感应对话时是以斜体标识的，以区别口头交谈，为什么修改版替换为粗体，是不是因为斜体在读取epub的阅读设备里不方便显示？如果是这方面的考量我也改为采取粗体标识，而且修改版某些句子没有正确使用粗体符号，导致文字没有变为粗体，需不需要进行修改？比如：
> 
> > 第三位管理员，T17SlU2⊃千数-植花者，加入了声音：
> 
> > **||ξ·相较于具体事务和智慧生命的生存，互惠原则未必是个重要考量|ν+·我们应该毫不犹豫地寻求盟友的帮助|ν·我们应该将此事呈报共识/理解者、共识/真理-追寻者和共识/群星-航行者进行审议|ο·我们不应该太快否定指控的价值：我们可以先对他们提出一些微不足道的指控，并监控他们的反应≈放走猎物以捕捉猎人
> 
> > 良子在做好充分准备后，如此说道。**ξ·如你们所知，这关系到我们种族的生存——虽然听起来可能有些自私，但我恳求你们一定要竭尽全力阻止/思考-保护者的种族灭绝行径|ξ+·毕竟你们的力量、资源远超过我们
> 
> > **μ!·这是一种极为意外的强大力量|μ+∈？·你说你迫使舰队穿过虫洞返回——进入了当地的恒星或奇点？|μ+∈·我们被告知舰队已被摧毁了

是的，所有的斜体被替换为粗体，这是因为中文中的斜体效果不好，具体参考维基百科中文翻译说明（晚点吾辈有电脑再补链接）。

至于渲染之后出现 **，这是错误，需要被修复，等晚点回去用电脑修复一下。

**Comment by rxliuli** [comment]
> 这些文字错误、错误粗体符号在github和网站上同时存在，需不需要我来核实校对并PR？可以的话我会采取修改版翻译为底稿并逐一进行正确修订

任何粗体错误请直接提 pr 修改（也许是 mark-magic 的一个 bug，晚上回去 check 一样）。关于文本错误，如果检查原文确定存在漏翻，也请直接提 pr 修复。

**Comment by iolliotier** [comment]
已提交，请查看https://github.com/liuli-moe/to-the-stars/pull/43/

**Comment by bixudamajiang** [comment]
我在[006-原作者参与的一些讨论.md](../tree/main/books/99/006-原作者参与的一些讨论.md)中看到了“悲叹魔方”的字样，我想知道这是谁翻译的，以及是否要修改这个翻译
> 如果没有 MSY 的调解和训练，这事情非常严肃，同时超过 6 到 7 人的团队会开始因为性格不合或<mark>悲叹魔方</mark>的分配而陷入争斗。
---
> 关于<mark>悲叹魔方</mark>系统如何支持 MSY 的运营：
---
> 1）  <mark>悲叹魔方</mark>比悲叹之种小得多。这使得欺骗他人变得更加困难，内讧的可能性也大大降低，因为每个人都可以直接拿走自己的份额。
---
> 魔法少女与金钱（甚至<mark>悲叹魔方</mark>经济学）的互动其实是一个相当有趣的话题，你可以想象一些疯狂的事情。事实上，我甚至在这里提出了一些建议：

**Comment by rxliuli** [comment]
> 我在[006-原作者参与的一些讨论.md](../tree/main/books/99/006-%E5%8E%9F%E4%BD%9C%E8%80%85%E5%8F%82%E4%B8%8E%E7%9A%84%E4%B8%80%E4%BA%9B%E8%AE%A8%E8%AE%BA.md)中看到了“悲叹魔方”的字样，我想知道这是谁翻译的，以及是否要修改这个翻译
> 
> > 如果没有 MSY 的调解和训练，这事情非常严肃，同时超过 6 到 7 人的团队会开始因为性格不合或悲叹魔方的分配而陷入争斗。
> 
> > 关于悲叹魔方系统如何支持 MSY 的运营：
> 
> > 1）  悲叹魔方比悲叹之种小得多。这使得欺骗他人变得更加困难，内讧的可能性也大大降低，因为每个人都可以直接拿走自己的份额。
> 
> > 魔法少女与金钱（甚至悲叹魔方经济学）的互动其实是一个相当有趣的话题，你可以想象一些疯狂的事情。事实上，我甚至在这里提出了一些建议：

似乎是贴吧的某位用户翻译，悲叹魔方的翻译只是，之前众所周知的**约定**。如果你愿意提 PR，那么就可以修改。
https://tieba.baidu.com/p/6475187247?client_type=2&client_version=11.1.8.1&fr=share&red_tag=1614313307&see_lz=1&sfc=copy&share=9105&st=1581062169&unique=29083D3527CBA8ADBDB751AB8309EBF0
