### ISSUE TITLE
建议删除首页的「概要」部分

### ISSUE THREAD

**Issue by andylizi** [liuli-moe/to-the-stars#54]
首页与第一章是每个潜在新读者接触 TTS 的第一印象。从这个角度来说，我感觉 8df0a20149c7ea2018ed073893f99ad1e7206d7b 为首页加入的概要内容存在一些问题：

* 虽然名字叫做概要，但它并没有概括任何故事情节，对新读者来说不知所云
* 翻译质量低
* 这些文字[并非作者本人所写](https://tts.determinismsucks.net/w/index.php?title=To_the_Stars&diff=prev&oldid=775)，而是 wiki 编辑者的创作与解读，有猜测的成分，不能代表“原作（canon）”或者作者（Word of God）的观点
  * 就算他的分析都是对的，这种“阅读理解”也不适宜作为原作文本的一部分出现，尤其是在首页这么显著的位置

综合来看，这一部分可能删掉或改成番外更加合适。

**Comment by rxliuli** [comment]
提个 pr？吾辈还在外面旅行中没有电脑可用😖
