### ISSUE TITLE
“Field Marshal”(元帅)(战区元帅)的译名问题

### ISSUE THREAD

**Issue by bixudamajiang** [liuli-moe/to-the-stars#57]
我发现LidaRyen的译文中，“Field Marshal”被译为了“战区元帅”，但是译文对照表又是“元帅”，请问是否需要对照原文进行更改？有一些地方则又是“元帅”一词，请问需要对这些地方进行更改吗？

---

> No one exemplifies this influx of new blood more than the current Chair of the General Staff,  `Field Marshal` Erwynmark, Hero of Aurelia and Sahara, whose current position caps a meteoric, decade‐long rise from Brigadier General of Volunteers.

> 最能代表那些新鲜血液的就是现任总参谋长，拯救奥勒利亚和撒哈拉的英雄，鄂温马克`战区元帅`。他能从一位民兵准将升到今天的位置，完全是他十年来赫赫战功的证明。

---

> If you say so, Machina, Mami thought. Sometimes she thought Machina rather liked the `Field Marshal` , which had some possibly disturbing implications.

> 就当是这么回事吧，麻美说。有时候她觉得机械娘挺喜欢那位`元帅`的，这其中的意味让麻美觉得不太舒服。

**Comment by andylizi** [comment]
如果我没记错的话，"战区元帅" 应该是 LidaRyen 的误译，很久以前就有人指出了，但旧译名看起来没有完全更新。确实应当统一一下。

**Comment by bixudamajiang** [comment]
那我要改成哪一种呢，我最近在重看，顺便订正一些译文
