### ISSUE TITLE
由070中“志筑奈奈”、“龙”发起向作者的询问

### ISSUE THREAD

**Issue by bixudamajiang** [liuli-moe/to-the-stars#78]
由于作者可能急于发布，忘记校对，所以 Kuroi nana（黑井奈奈）可能打成了 Shizuki nana（志筑奈奈）。
070：
![图片](https://github.com/user-attachments/assets/01d4ba68-e20f-47b0-abd3-da2dce44fa3c)

同时，070中出现了一个“龙”
![图片](https://github.com/user-attachments/assets/7f514edb-9c07-4b34-9ea7-168b6ce0f9af)

这个“龙”可能需要考证一下是什么龙（当然也有可能保留多义项）

**Comment by rxliuli** [comment]
原作相关的问题需要到 Discord 群组讨论，吾辈没有权限邀请。。。也许你可以在 Twitter 上私信作者要邀请链接

https://x.com/ttshieronym/status/1776807976038285497

**Comment by iolliotier** [comment]
原来志筑奈奈（Shizuki nana）是作者打错了啊，之前还奇怪良子的姑姑怎么和良子一个姓，我改一下

**Comment by bixudamajiang** [comment]
低情商：作者打错了。
高情商：其实暗示奈奈和良子父亲有一腿（

**Comment by iolliotier** [comment]
作者现在也没有改，还需要改动吗？

**Comment by bixudamajiang** [comment]
我不知道，我只是提议问一下，可能真的有伏笔呢（




                       
原始邮件
                       
                     

发件人："ionaoter"< ***@***.*** &gt;;

发件时间：2024/8/21 14:58

收件人："liuli-moe/to-the-stars"< ***@***.*** &gt;;

抄送人："bixudamajiang"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [liuli-moe/to-the-stars] 由070中“志筑奈奈”、“龙”发起向作者的询问 (Issue #78)




 
作者现在也没有改，还需要改动吗？
